version: '3.9'

services:
  postgres:
    build: ./postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: eezimin
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5430:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eezimin -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  spark:
    build: ./spark
    container_name: spark_container
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - ./notebooks:/workspace/notebooks
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
    driver: local